[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
ctor = "0.2.9"
frame = { path = "../frame" }
frame_support = { path = "../frame_support" }
lazy_static = "1.5.0"
log = "0.4.22"
log4rs = "1.3.0"
