[package]
name = "frame"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
ctor = "0.2.9"
lazy_static = "1.5.0"
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = {version="2.0.91",features = ["full"]}
